[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeometricKalman = "37c64ece-753e-4456-a3c8-f0622d3cd54c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Distributions = "0.22.6, 0.23, 0.24, 0.25"
GeometricKalman = "0.1"
IJulia = "1"
Manifolds = "0.11"
ManifoldsBase = "2"
Plots = "1"
RecursiveArrayTools = "3"
SpecialFunctions = "2"
StaticArrays = "1"

[sources]
GeometricKalman = { path = ".." }
